---
 - name: check & view result
   become: true
   shell: systemctl status openvpn
   register: status_openvpn_service
  
 - name: view result service
   debug: var="status_openvpn_service.stdout_lines"
