---
 - name: install openvpn & dependensis
   apt:
    name: "{{packages}}"
    cache_valid_time: 3600
    update_cache: true
    force: true
   vars:
     packages:
      - udev
      - openvpn=2.3.10-1ubuntu2.1
      - openssl
      - zip

...
